name: scroll_to_hide
description: Scroll_To_Hide packge to hide widgets on scroll.
version: 1.0.0
homepage: https://github.com/ElG0hary/scroll_to_hide.git

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
