name: scroll_to_hide
description: A Flutter widget that hides or shows any child when the user scrolls.
version: 2.3.0
homepage: https://github.com/ElG0hary/scroll_to_hide
repository: https://github.com/ElG0hary/scroll_to_hide

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
